spring.application.name=NoSQL_Database_Management_System
server.port=8081
node.name=worker1
node.workerPath = http://worker1:8081
bootstrap.url=http://bootstrap:8080
admin.username=admin
admin.token=admin123