spring.application.name=NoSQL_Database_Management_System
server.port=8082
node.name=worker2
node.workerPath = http://worker2:8082
bootstrap.url=http://bootstrap:8080
admin.username=admin
admin.token=admin123